#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2016 by Burkhardt Renz. All rights reserved.
# Makes App for Mac OSX
# ----------------------------------------------------------------------------

javapackager -deploy -name eBC -appclass ebc.main \
	-native dmg -outdir target -outfile eBC -srcdir ./target -srcfiles ebc.jar -v
